No configuration file found.
No pyproject.toml file found.
stubPath /mnt/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/04ea108c9eb5ed564651c4c95e4c7400d6641059/typings is not a valid directory.
Assuming Python platform Linux
Searching for source files
Found 1 source file
/home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/04ea108c9eb5ed564651c4c95e4c7400d6641059/a/run_experiment.py
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/04ea108c9eb5ed564651c4c95e4c7400d6641059/a/run_experiment.py:2:8 - error: Import "sacred" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/04ea108c9eb5ed564651c4c95e4c7400d6641059/a/run_experiment.py:11:8 - warning: Import "requests" could not be resolved from source (reportMissingModuleSource)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/04ea108c9eb5ed564651c4c95e4c7400d6641059/a/run_experiment.py:13:6 - error: Import "configs" could not be resolved (reportMissingImports)
2 errors, 1 warning, 0 infos 
Completed in 1.331sec

time cost(in seconds): 1.4595916271209717
