No configuration file found.
No pyproject.toml file found.
stubPath /mnt/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/typings is not a valid directory.
Assuming Python platform Linux
Searching for source files
Found 8 source files
/home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/scripts/dump_train_config.py
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/scripts/dump_train_config.py:7:8 - error: Import "cv2" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/scripts/dump_train_config.py:10:8 - error: Import "tqdm" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/scripts/dump_train_config.py:12:6 - error: Import "tensorpack.utils" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/scripts/dump_train_config.py:13:6 - error: Import "tensorpack.utils.fs" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/scripts/dump_train_config.py:14:6 - error: Import "tensorpack.dataflow" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/scripts/dump_train_config.py:30:65 - error: Cannot access member "get_config" for type "ModuleType"
    Member "get_config" is unknown (reportGeneralTypeIssues)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/scripts/dump_train_config.py:49:6 - error: "RepeatedData" is not defined (reportUndefinedVariable)
/home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/tensorpack/dataflow/common.py
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/tensorpack/dataflow/common.py:9:6 - warning: Import "six.moves" could not be resolved from source (reportMissingModuleSource)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/tensorpack/dataflow/common.py:10:6 - error: Import ".base" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/tensorpack/dataflow/common.py:319:24 - error: Operator "-" not supported for "None" (reportOptionalOperand)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/tensorpack/dataflow/common.py:324:22 - error: No overloads for "__init__" match the provided arguments
    Argument types: (int | None) (reportGeneralTypeIssues)
/home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/tensorpack/dataflow/dataset/ilsvrc.py
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/tensorpack/dataflow/dataset/ilsvrc.py:7:8 - error: Import "cv2" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/tensorpack/dataflow/dataset/ilsvrc.py:9:6 - warning: Import "six.moves" could not be resolved from source (reportMissingModuleSource)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/tensorpack/dataflow/dataset/ilsvrc.py:13:6 - error: Import "...utils.loadcaffe" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/tensorpack/dataflow/dataset/ilsvrc.py:14:6 - error: Import "...utils.fs" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/tensorpack/dataflow/dataset/ilsvrc.py:15:6 - error: Import "...utils.timer" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/tensorpack/dataflow/dataset/ilsvrc.py:16:6 - error: Import "..base" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/tensorpack/dataflow/dataset/ilsvrc.py:226:14 - error: Import "IPython" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/tensorpack/dataflow/dataset/ilsvrc.py:202:20 - error: Import "tqdm" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/tensorpack/dataflow/dataset/ilsvrc.py:12:30 - error: "get_rng" is unknown import symbol (reportGeneralTypeIssues)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/tensorpack/dataflow/dataset/ilsvrc.py:12:39 - error: "get_dataset_dir" is unknown import symbol (reportGeneralTypeIssues)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/tensorpack/dataflow/dataset/ilsvrc.py:12:56 - error: "memoized" is unknown import symbol (reportGeneralTypeIssues)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/tensorpack/dataflow/dataset/ilsvrc.py:21:25 - error: "warn" is not a known member of module (reportGeneralTypeIssues)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/tensorpack/dataflow/dataset/ilsvrc.py:189:38 - error: Cannot access member "getchildren" for type "Element"
    Member "getchildren" is unknown (reportGeneralTypeIssues)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/tensorpack/dataflow/dataset/ilsvrc.py:189:38 - error: "getchildren" is not a known member of "None" (reportOptionalMemberAccess)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/tensorpack/dataflow/dataset/ilsvrc.py:192:39 - error: "find" is not a known member of "None" (reportOptionalMemberAccess)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/tensorpack/dataflow/dataset/ilsvrc.py:192:54 - error: Cannot access member "getchildren" for type "Element"
    Member "getchildren" is unknown (reportGeneralTypeIssues)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/tensorpack/dataflow/dataset/ilsvrc.py:192:54 - error: "getchildren" is not a known member of "None" (reportOptionalMemberAccess)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/tensorpack/dataflow/dataset/ilsvrc.py:194:13 - error: "__getitem__" method not defined on type "map[float]" (reportGeneralTypeIssues)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/tensorpack/dataflow/dataset/ilsvrc.py:194:23 - error: "__getitem__" method not defined on type "map[int]" (reportGeneralTypeIssues)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/tensorpack/dataflow/dataset/ilsvrc.py:194:13 - error: "__setitem__" method not defined on type "map[float]" (reportGeneralTypeIssues)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/tensorpack/dataflow/dataset/ilsvrc.py:195:13 - error: "__getitem__" method not defined on type "map[float]" (reportGeneralTypeIssues)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/tensorpack/dataflow/dataset/ilsvrc.py:195:23 - error: "__getitem__" method not defined on type "map[int]" (reportGeneralTypeIssues)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/tensorpack/dataflow/dataset/ilsvrc.py:195:13 - error: "__setitem__" method not defined on type "map[float]" (reportGeneralTypeIssues)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/tensorpack/dataflow/dataset/ilsvrc.py:196:13 - error: "__getitem__" method not defined on type "map[float]" (reportGeneralTypeIssues)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/tensorpack/dataflow/dataset/ilsvrc.py:196:23 - error: "__getitem__" method not defined on type "map[int]" (reportGeneralTypeIssues)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/tensorpack/dataflow/dataset/ilsvrc.py:196:13 - error: "__setitem__" method not defined on type "map[float]" (reportGeneralTypeIssues)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/tensorpack/dataflow/dataset/ilsvrc.py:197:13 - error: "__getitem__" method not defined on type "map[float]" (reportGeneralTypeIssues)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/tensorpack/dataflow/dataset/ilsvrc.py:197:23 - error: "__getitem__" method not defined on type "map[int]" (reportGeneralTypeIssues)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/tensorpack/dataflow/dataset/ilsvrc.py:197:13 - error: "__setitem__" method not defined on type "map[float]" (reportGeneralTypeIssues)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/tensorpack/dataflow/dataset/ilsvrc.py:214:20 - error: "info" is not a known member of module (reportGeneralTypeIssues)
/home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/tensorpack/dataflow/imgaug/crop.py
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/tensorpack/dataflow/imgaug/crop.py:5:6 - error: Import ".base" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/tensorpack/dataflow/imgaug/crop.py:8:6 - warning: Import "six.moves" could not be resolved from source (reportMissingModuleSource)
/home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/tensorpack/dataflow/imgaug/imgproc.py
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/tensorpack/dataflow/imgaug/imgproc.py:5:6 - error: Import ".base" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/tensorpack/dataflow/imgaug/imgproc.py:7:8 - error: Import "cv2" could not be resolved (reportMissingImports)
/home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/tensorpack/dataflow/imgaug/meta.py
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/tensorpack/dataflow/imgaug/meta.py:7:6 - error: Import ".base" could not be resolved (reportMissingImports)
/home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/tensorpack/utils/logger.py
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/tensorpack/utils/logger.py:10:6 - warning: Import "six.moves" could not be resolved from source (reportMissingModuleSource)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/tensorpack/utils/logger.py:13:6 - error: Import ".fs" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/tensorpack/utils/logger.py:52:9 - error: "info" is not defined (reportUndefinedVariable)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/tensorpack/utils/logger.py:76:13 - error: "info" is not defined (reportUndefinedVariable)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/tensorpack/utils/logger.py:81:13 - error: "info" is not defined (reportUndefinedVariable)
/home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/tensorpack/utils/rect.py
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/tensorpack/utils/rect.py:104:11 - error: Statements must be separated by newlines or semicolons
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/4af483993c629deb6f49f249ddf060a3ae483ff3/a/tensorpack/utils/rect.py:105:11 - error: Statements must be separated by newlines or semicolons
49 errors, 4 warnings, 0 infos 
Completed in 2.12sec

time cost(in seconds): 2.2555782794952393
