/home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/huggingface_transformers/1d5ea34f6abd0b62ed89a8d5fa4cc14ed970cf67/a/src/transformers/trainer_callback.py:19: error: Library stubs not installed for "dataclasses" (or incompatible with Python 3.6)
/home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/huggingface_transformers/1d5ea34f6abd0b62ed89a8d5fa4cc14ed970cf67/a/src/transformers/trainer_callback.py:19: note: Hint: "python3 -m pip install types-dataclasses"
/home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/huggingface_transformers/1d5ea34f6abd0b62ed89a8d5fa4cc14ed970cf67/a/src/transformers/trainer_callback.py:19: note: (or run "mypy --install-types" to install all missing stub packages)
/home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/huggingface_transformers/1d5ea34f6abd0b62ed89a8d5fa4cc14ed970cf67/a/src/transformers/trainer_callback.py:19: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
/home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/huggingface_transformers/1d5ea34f6abd0b62ed89a8d5fa4cc14ed970cf67/a/src/transformers/trainer_callback.py:24: error: Cannot find implementation or library stub for module named "tqdm.auto"
/home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/huggingface_transformers/1d5ea34f6abd0b62ed89a8d5fa4cc14ed970cf67/a/src/transformers/trainer_callback.py:26: error: Skipping analyzing ".trainer_utils": found module but no type hints or library stubs
/home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/huggingface_transformers/1d5ea34f6abd0b62ed89a8d5fa4cc14ed970cf67/a/src/transformers/trainer_callback.py:27: error: Skipping analyzing ".training_args": found module but no type hints or library stubs
/home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/huggingface_transformers/1d5ea34f6abd0b62ed89a8d5fa4cc14ed970cf67/a/src/transformers/trainer_callback.py:28: error: Skipping analyzing ".utils": found module but no type hints or library stubs
/home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/huggingface_transformers/1d5ea34f6abd0b62ed89a8d5fa4cc14ed970cf67/a/src/transformers/trainer_callback.py:76: error: Incompatible types in assignment (expression has type "None", variable has type "List[Dict[str, float]]")
/home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/huggingface_transformers/1d5ea34f6abd0b62ed89a8d5fa4cc14ed970cf67/a/src/transformers/trainer_callback.py:97: error: Too many arguments for "TrainerState"
/home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/huggingface_transformers/1d5ea34f6abd0b62ed89a8d5fa4cc14ed970cf67/a/src/transformers/trainer_callback.py:324: error: Signature of "on_init_end" incompatible with supertype "TrainerCallback"
/home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/huggingface_transformers/1d5ea34f6abd0b62ed89a8d5fa4cc14ed970cf67/a/src/transformers/trainer_callback.py:327: error: Signature of "on_train_begin" incompatible with supertype "TrainerCallback"
/home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/huggingface_transformers/1d5ea34f6abd0b62ed89a8d5fa4cc14ed970cf67/a/src/transformers/trainer_callback.py:331: error: Signature of "on_train_end" incompatible with supertype "TrainerCallback"
/home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/huggingface_transformers/1d5ea34f6abd0b62ed89a8d5fa4cc14ed970cf67/a/src/transformers/trainer_callback.py:334: error: Signature of "on_epoch_begin" incompatible with supertype "TrainerCallback"
/home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/huggingface_transformers/1d5ea34f6abd0b62ed89a8d5fa4cc14ed970cf67/a/src/transformers/trainer_callback.py:338: error: Signature of "on_epoch_end" incompatible with supertype "TrainerCallback"
/home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/huggingface_transformers/1d5ea34f6abd0b62ed89a8d5fa4cc14ed970cf67/a/src/transformers/trainer_callback.py:341: error: Signature of "on_step_begin" incompatible with supertype "TrainerCallback"
/home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/huggingface_transformers/1d5ea34f6abd0b62ed89a8d5fa4cc14ed970cf67/a/src/transformers/trainer_callback.py:347: error: Signature of "on_step_end" incompatible with supertype "TrainerCallback"
/home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/huggingface_transformers/1d5ea34f6abd0b62ed89a8d5fa4cc14ed970cf67/a/src/transformers/trainer_callback.py:350: error: Signature of "on_evaluate" incompatible with supertype "TrainerCallback"
/home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/huggingface_transformers/1d5ea34f6abd0b62ed89a8d5fa4cc14ed970cf67/a/src/transformers/trainer_callback.py:354: error: Signature of "on_save" incompatible with supertype "TrainerCallback"
/home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/huggingface_transformers/1d5ea34f6abd0b62ed89a8d5fa4cc14ed970cf67/a/src/transformers/trainer_callback.py:358: error: Signature of "on_log" incompatible with supertype "TrainerCallback"
/home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/huggingface_transformers/1d5ea34f6abd0b62ed89a8d5fa4cc14ed970cf67/a/src/transformers/trainer_callback.py:362: error: Signature of "on_prediction_step" incompatible with supertype "TrainerCallback"
Found 18 errors in 1 file (checked 1 source file)

time cost(in seconds): 0.48644042015075684
