No configuration file found.
No pyproject.toml file found.
stubPath /mnt/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/ae84b52ad5402ab1716e0f1e9790ce1da9d706d1/typings is not a valid directory.
Assuming Python platform Linux
Searching for source files
Found 1 source file
/home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/ae84b52ad5402ab1716e0f1e9790ce1da9d706d1/a/tensorpack/dataflow/image.py
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/ae84b52ad5402ab1716e0f1e9790ce1da9d706d1/a/tensorpack/dataflow/image.py:6:8 - error: Import "cv2" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/ae84b52ad5402ab1716e0f1e9790ce1da9d706d1/a/tensorpack/dataflow/image.py:8:6 - error: Import ".base" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/ae84b52ad5402ab1716e0f1e9790ce1da9d706d1/a/tensorpack/dataflow/image.py:9:6 - error: Import ".common" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/ae84b52ad5402ab1716e0f1e9790ce1da9d706d1/a/tensorpack/dataflow/image.py:10:6 - error: Import ".imgaug" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/ae84b52ad5402ab1716e0f1e9790ce1da9d706d1/a/tensorpack/dataflow/image.py:11:6 - error: Import "..utils" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorpack_tensorpack/ae84b52ad5402ab1716e0f1e9790ce1da9d706d1/a/tensorpack/dataflow/image.py:12:6 - error: Import "..utils.argtools" could not be resolved (reportMissingImports)
6 errors, 0 warnings, 0 infos 
Completed in 0.966sec

time cost(in seconds): 1.117415189743042
