No configuration file found.
No pyproject.toml file found.
stubPath /mnt/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/davidsandberg_facenet/c39be02589d9cfa08b673d2bae20cde160305c8a/typings is not a valid directory.
Assuming Python platform Linux
Searching for source files
Found 1 source file
/home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/davidsandberg_facenet/c39be02589d9cfa08b673d2bae20cde160305c8a/a/facenet/src/facenet.py
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/davidsandberg_facenet/c39be02589d9cfa08b673d2bae20cde160305c8a/a/facenet/src/facenet.py:10:6 - warning: Import "six.moves" could not be resolved from source (reportMissingModuleSource)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/davidsandberg_facenet/c39be02589d9cfa08b673d2bae20cde160305c8a/a/facenet/src/facenet.py:15:6 - error: Import "scipy" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/davidsandberg_facenet/c39be02589d9cfa08b673d2bae20cde160305c8a/a/facenet/src/facenet.py:16:8 - error: Import "matplotlib.pyplot" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/davidsandberg_facenet/c39be02589d9cfa08b673d2bae20cde160305c8a/a/facenet/src/facenet.py:17:6 - error: Import "sklearn.cross_validation" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/davidsandberg_facenet/c39be02589d9cfa08b673d2bae20cde160305c8a/a/facenet/src/facenet.py:662:10 - error: "tpr" is possibly unbound (reportUnboundVariable)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/davidsandberg_facenet/c39be02589d9cfa08b673d2bae20cde160305c8a/a/facenet/src/facenet.py:662:15 - error: "fpr" is possibly unbound (reportUnboundVariable)
5 errors, 1 warning, 0 infos 
Completed in 1.841sec

time cost(in seconds): 2.030128240585327
